number=int(input('ingres an even number:'))
print('your triangle area is:',number*number/2 )
print('your rectangle area is:',number*number)
apotema=int(input('ingresa tu apotema:'))
print('your pentagon area is:',number*5*apotema/2)
print('................................')
Number=int(input('ingres a number:'))
print('your circle area is:',Number*2*3.14)
number2=int(input('ingres other number:'))
print('your trapezoide area is:',Number*number2*number)