print("how can we act with empathy and positivity when we are online")
print("support and treat people with kidness in internet")
print("identify")
print("the boy wrote a letter to a girl and that girl publish the pic in her insta and then people started laughing at the boy and he had to change school")
print("feel")
print("the girl is feeling gulty because the boy got bully, the boy is feeling sad, ")
print("imagine")
print("the girl just tell the boy no, and she dont publish anything, the people dont take it funny, the friends of the girl dont share the pic")
print("say")
print("the boy wouldnt change school, the girl wouldt feel guilty")
